title: Meow !, LeaveCat Blog
email: leavecat.union@gmail.com
description: >
	LeaveCat is korean young child hacking team.
baseurl: "/"
url: "http://blog.leave.cat"
github_username:  LeaveCat

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
